config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pictures do 
    get :big_picture, :on => :member
  end

  root :to => "pictures#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_one_attached :file
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if:  :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :big_picture]
  before_action :set_picture, only: [:show, :edit, :update, :destroy, :big_picture]


  def index
    @pictures = user_signed_in? ? current_user.pictures : Picture.all
  end

  def show
  end

  def new
    @picture = Picture.new
  end

  def edit 
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to picture_path(@picture), notice: 'The Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_path, notice: 'The picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user = current_user

    respond_to do |format|
      if @picture.save
        format.html { redirect_to pictures_path, notice: 'The Picture was successfully added.' }
        format.json { render :index, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def big_picture
    p params
    respond_to do |format|
      format.js
      format.html
    end
  end
  
  private 

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:description, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="home">
    <%= link_to root_path do %>
      <i class="fas fa-home"></i>
    <% end %>
  </div>
  <div class="log-items">
    <% if user_signed_in? %>
    <%= link_to 'Edit account', edit_user_registration_path, class: "navbar-item" %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "navbar-item") %> 
    <% else %>
      <%= link_to('Login', new_user_session_path, class: "navbar-item") %> 
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicsUs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pictures/_big_picture.html.erb
<div class="modal-header">
  <div class="picture-meta">
    <strong>File name :</strong> <%= @picture.file.blob.filename %> -
    <strong>File type :</strong> <%= @picture.file.blob.content_type %>
  </div>
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body" style="background-image: url('<%= url_for(@picture.file)%>')">
</div>

app/views/pictures/_form.html.erb
<%= form_for @picture do |f| %>
  <div class="field">
    <%= f.label :file %> <br>
    <%= f.file_field :file %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <%= f.submit :submit, class: 'btn btn-success' %>
<% end %>

app/views/pictures/_random_picture_list.html.erb
<div class="pictures-wrapper">
  <h1>Welcome to PicsUp</h1>
  <% unless @pictures.blank? %>
    <div class="picture-container">
      <% Picture.order("RANDOM()").limit(3).each do |picture| %>
        <div class="picture-card">
          <%= link_to big_picture_picture_path(picture, format: :js), :remote => true , data: {'toggle' =>  "modal", 'target' => '#modal-window'} do %>
            <div class="picture" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('<%= url_for(picture.file)%>')">
          </div>
          <% end %>
          
          <div class="description">
            <%= "Description : #{picture.description}" %>
          </div>
      </div>
      <% end %>
    </div>
  <% end %>

  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content"></div>
      </div>
  </div>
</div>

app/views/pictures/_user_picture_list.html.erb
<div class="pictures-wrapper">
    <h1>Hi <%= current_user.name %> ! Here is you're picture list ! </h1>
    <div class="picture-container">
      <% @pictures.each do |picture| %>
      <div class="picture-card">
        <div class="actions">
          <%= link_to picture_path(picture) do %>
            <i class="far fa-eye"></i>
          <% end %>
          <%= link_to picture_path(picture), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </div>
        <%= link_to big_picture_picture_path(picture, format: :js), :remote => true , data: {'toggle' =>  "modal", 'target' => '#modal-window'} do %>
          <div class="picture" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('<%= url_for(picture.file)%>')">
        </div>
        <% end %>
        
        <div class="description">
          <%= "Description : #{picture.description}" %>
        </div>
    </div>
      <% end %>
    </div>
<%= link_to 'Add picture', new_picture_path, class: "btn btn-info" %>
</div>
  


<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>

app/views/pictures/big_picture.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'pictures/big_picture' %>");
$("#modal-window").modal('show');

app/views/pictures/edit.html.erb
<div class="picture-form-container">
  <div class="picture-form">

    <h2>Edit picture</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/pictures/index.html.erb
<% if user_signed_in? %>
	<%= render 'user_picture_list' %>
<% else %>
	<%= render 'random_picture_list' %>
<% end %>

app/views/pictures/new.html.erb
<div class="picture-form-container">
  <div class="picture-form">

    <h2>New picture</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="picture-big">
  <div class="actions">
    <%= link_to pictures_path, class: 'btn btn-info' do %>
    <i class="fas fa-arrow-left"></i> Return to picture list
  <% end %>
  <%= link_to 'Edit picture', edit_picture_path(@picture), class: 'btn btn-success' %>
  </div>
  <div class="image">
    <%= image_tag(@picture.file) %>
  </div>
  <div class="description">
    <strong>Description</strong> : <%= @picture.description %>
  </div>
</div>